### ISSUE TITLE
Step 8's step 8.1 type-error

### ISSUE THREAD

**Issue by TVaakanainen** [Urigo/WhatsApp-Clone-Client-React#1009]
```
Type 'MutationFn<unknown, OperationVariables>' is not an array type.  TS2461

    69 |   });
    70 |
  > 71 |   const [addMessage] = useMutation(addMessageMutation);
       |         ^
    72 |
    73 |   const onSendMessage = useCallback(
    74 |     (content: string) => {
```

I think line 71 should actually be `const addMessage = useMutation(addMessageMutation);`

**Comment by TVaakanainen** [comment]
Also on step 8.2 on ChatList test update import for getChatsQuery should be removed as on the next code-block it is completely removed.

**Comment by milenazuccarelli** [comment]
Experiencing same issue, however, I don't think the square braces are the problem here

**Comment by Urigo** [comment]
@TVaakanainen @milenazuccarelli what version of `react-apollo-hooks` are you using?

I believe that on the latest version (0.5.0) it is suppose to work like [that](https://github.com/trojanowski/react-apollo-hooks/commit/e0d05fda6bff8f035f17c4e389dabf7268f7b0ec)

@TVaakanainen about the import, can you point me to the line of code? I couldn't fully understand what you meant

**Comment by milenazuccarelli** [comment]
I'm using version 0.5.0, but getting this type error too for some reason, although it compiles fine

**Comment by Urigo** [comment]
We've now moved to the new `@apollo/react-hooks`
