### ISSUE TITLE
Step 9.2 issue: Cannot read property '__typename' of undefined

### ISSUE THREAD

**Issue by milenazuccarelli** [Urigo/WhatsApp-Clone-Client-React#1037]
Hi,

In step 9.2: Use Codegen Hooks, I'm was running into the following error while trying to send a message. Line 85 of `src/components/ChatRoomScreen/index.tsx`: 
`const chatIdFromStore = defaultDataIdFromObject(addMessage.chat);`
produces the following error: 
`Cannot read property '__typename' of undefined`. 

The update function for the addMessage mutation expects the Message result to have some details about the chat. The Message.chat resolver is only introduced in the server in chapter 10 at Step 7.7: Add Message.chat resolver.

I made the following changes for now:

Line 85 in the the ChatRoomScreen index, changed
`const chatIdFromStore = defaultDataIdFromObject(addMessage.chat);` to
`const chatIdFromStore = defaultDataIdFromObject(chat);`

Line 103 changed
`if (fullChat.messages.messages.some((m: any) => m.id === addMessage.id)) return;` to
`if (fullChat.messages.some((m: any) => m.id === addMessage.id)) return;`

Line 105 changed
`fullChat.messages.messages.push(addMessage);` to
`fullChat.messages.push(addMessage);`

Happy to submit a PR to fix this if need be :-)

**Comment by Urigo** [comment]
@milenazuccarelli you are right, it was broken.
I've fixed it and deployed a new version and added you to the contributors on the bottom of the README

Thank you!
