### ISSUE TITLE
This is a web app? not mobile app?

### ISSUE THREAD

**Issue by pancake-boy** [Urigo/WhatsApp-Clone-Client-React#1080]
why do i see some screenshots (like in step 2) that the chat list is inside a mobile phone simulator? but no where did it mention anything about that?

**Comment by veerjainATgmail** [comment]
> why do i see some screenshots (like in step 2) that the chat list is inside a mobile phone simulator? but no where did it mention anything about that?

Its a web application. The UX is similar to WhatsApp mobile App.

**Comment by Urigo** [comment]
We do plan to change it to also be a react-native app, you can track it here: https://github.com/Urigo/WhatsApp-Clone-Client-React/issues/51
