### ISSUE TITLE
yarn test - 'TZ' is not recognized as an internal or external command

### ISSUE THREAD

**Issue by peterennis** [Urigo/WhatsApp-Clone-Client-React#1195]
Windows 10

```
C:\ae\ae-whatsapp-clone\WhatsApp-Clone-Client-React>yarn test
yarn run v1.17.3
$ TZ="Asia/Jerusalem" react-scripts test
'TZ' is not recognized as an internal or external command,
operable program or batch file.
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

C:\ae\ae-whatsapp-clone\WhatsApp-Clone-Client-React>
```

**Comment by micahgoodreau** [comment]
for windows, in the package.json file change the test line under scripts to:
"test": "SET TZ=\"Asia/Jerusalem\" && jest --runInBand --forceExit",

**Comment by Urigo** [comment]
Fixed this on the new version, now using environment variable inside `.env.test`:
```
TZ=UTC
```

**Comment by Urigo** [comment]
will push the new version later today

**Comment by 6eniu5** [comment]
> for windows, in the package.json file change the test line under scripts to: "test": "SET TZ="Asia/Jerusalem" && jest --runInBand --forceExit",

actually, you need to escape the double quotes
`"SET TZ=\"UTC\" && jest"`

**Comment by mbirali** [comment]
You just need to start script with `jest` and remove other prefix before jest ! (worked for me!)
