### ISSUE TITLE
Failed to compile (Typescript Definitions Missing)

### ISSUE THREAD

**Issue by hugo4711** [Urigo/WhatsApp-Clone-Client-React#1505]
Failed to compile.

./src/graphql/fragments/index.ts
  Line 1:1:  Definition for rule '@typescript-eslint/consistent-type-assertions' was not found  @typescript-eslint/consistent-type-assertions
  Line 1:1:  Definition for rule '@typescript-eslint/no-unused-expressions' was not found       @typescript-eslint/no-unused-expressions

Search for the keywords to learn more about each error.

**Comment by Urigo** [comment]
Fixed in the new version, pushing in a couple of minutes
