### ISSUE TITLE
Graphql types and Babel

### ISSUE THREAD

**Issue by FredyC** [Urigo/WhatsApp-Clone-Client-React#61]
Wait, what? How did you manage that? :) I mean the TypeScript support in Babel does not support namespaces and yet your app clearly starts and does not complain about it. Is there some hidden switch I am failing to see that makes this magic happen? :)

**Comment by DAB0mB** [comment]
First of all, the Babel parser does support TypeScript namespace nodes (see [reference](https://babeljs.io/docs/en/babel-parser#language-extensions)), it's just that the the preset disables it for reasons I'm not familiar with. `create-react-app` however, will use the TypeScript compiler if a `tsconig` and `ts` files are provided, not the Babel preset. The Babel transformation will come after the TypeScript transformation, and will compile JSX code to JS. Hope this helps.

**Comment by FredyC** [comment]
Oh wow, thanks a lot for that. I was messing with `react-scripts-ts` fork which comes with additional hurdles for such a long time. I certainly do have to try this out soon.

**Comment by DAB0mB** [comment]
No don't use it, I also used it at the beginning, but `create-react-app` will do. We will explain that in the step-by-step tutorial

**Comment by FredyC** [comment]
@DAB0mB Hey, I am curious, is the tutorial available somewhere already?

I am currently trying to change the existing app to use `react-scripts` directly, but it's pretty much failing on `Namespaces are not supported`. 

I did manage to run your client app just fine even though namespaces are there obviously. There must be some little thing I am missing :)

I do have a tsconfig file. I've compared it to mine and it's pretty much same except I don't need decorators.

One thing I've noticed that in your project you don't actually have `typescript` dependency installed. I tried it without it, but it hasn't changed a thing.

Any idea what else could be wrong. This is some dark magic it seems :D

**Comment by FredyC** [comment]
Oh, I've found the actual culprit ... Enums 😮 

Only after I've removed all use of enum types, it has built the app no matter namespaces. When I try to use `MessageType` enum in your app, it fails the build as well.

**Comment by DAB0mB** [comment]
@FredyC This is how I setup `create-react-app` with TypeScript: https://tortilla.academy/tutorial/whatsapp-react/step/1
The tutorial that you see is a light version of a more upcoming robust one, but maybe you can find answers in there as for now. Do you try to use `MessageType` enum in the client? We don't have that in our app so I'm trying to understand, maybe you tried to set in manually. I might have a solution for you, I didn't try though, but it can help. Follow these steps:

- Run eject.
- Change TS target to compile to `esnext` or similar by setting the `target` field in your `tsconfig.json`.
- Apply Babel transformation on top of it by editing the WebPack config.

Let me know if I missed anything or if things work out for you.

**Comment by FredyC** [comment]
@DAB0mB Well, you do have a `MessageType` enum [in your schema](https://github.com/Urigo/WhatsApp-Clone-server/blob/master/db.ts#L10) which gets generated to the `types.ts` in the client. I tried to use in the client (no matter where) and suddenly the error about namespaces not supported pops out.

My guess that since enums are used in runtime, there is some other process that actually uses Babel to parse it and fails.

**Comment by FredyC** [comment]
So I've found an interesting approach to this problem. The `graphql-code-generator` has the `noNamespaces` option which is ugly on its own but solves the issue with CRA. 

There is also a nice plugin [react-apollo](https://graphql-code-generator.com/docs/plugins/typescript-react-apollo) to generate components/hooks based on documents which is awesome. What's more important though that since those non-namespaced types are bundled with generated code, I don't need to deal with them.

```
plugins: [
  'typescript-common',
  'typescript-client',
  'typescript-react-apollo',
],
config: {
  noNamespaces: true,
  noHOC: true,
  noComponents: true,
  withHooks: true,
}
```

There is only a [tiny detail](https://github.com/dotansimha/graphql-code-generator/issues/1336) that bothers, but otherwise it looks like a great solution indeed.

**Comment by FredyC** [comment]
Closing as I've battle tested this and works just fine :) Except some weirdness in Babel produced source maps (especially async functions), but that's a different story.
