### ISSUE TITLE
WebSocket connection to 'ws://localhost:4000/graphql' failed: Connection closed before receiving a handshake response

### ISSUE THREAD

**Issue by kenNg1** [Urigo/WhatsApp-Clone-Client-React#670]
I have cloned the server and client, following the instructions carefully. The folders are placed inside a parent folder called 'whatsapp-clone'.

When I run 'yarn start' on the server it appears to be running o.k.:
```
$ yarn codegen
$ gql-gen
  ✔ Parse configuration
  ✔ Generate outputs
$ ts-node index.ts
Server is listening on port 4000
```

But on http://localhost:3000/sign-up, I receive the error
```
WebSocket connection to 'ws://localhost:4000/graphql' failed: Connection closed before receiving a handshake response
```

Can you please suggest a fix? Thanks in advance

**Comment by Urigo** [comment]
it looks like somehow the client is not getting to the server...

Also, did you follow the steps for setting up the database and the users?

**Comment by kenNg1** [comment]
I fixed the problem by downgrading to node version 10.x.x. Thanks

**Comment by Urigo** [comment]
@kenNg1 that is super weird because we test it all with latest Node (12)....

Not sure if you'll have time for this but I would love to try to see what is your local issue. 
We can meet online and maybe do a session sharing the screen even
