### ISSUE TITLE
Jest junit package missing in tutorial steps (part 5, server)

### ISSUE THREAD

**Issue by TVaakanainen** [Urigo/WhatsApp-Clone-Client-React#905]
Steps that define packages to install in the tutorial are missing package jest-junit, however it is visible in package.json diff and it is utilized in test-script. 

So unless one notices this they are greeted with an error while trying to run the tests: `Error: Could not resolve a module for a custom reporter. Module name: jest-junit`

**Comment by Urigo** [comment]
thank you, I'll release a new version with the fix next week

**Comment by Urigo** [comment]
I think its fixed in the new `next` version, can you please confirm?

**Comment by rishabh2712** [comment]
I still am facing this problem

**Comment by rishabh2712** [comment]
`npm update `solved the issue. 
My bad I reported it.

**Comment by Urigo** [comment]
ohh so no need to update anything in the instructions?

Thank you @rishabh2712 !
