### ISSUE TITLE
Step 6 is missing types for react-router-dom in the steps

### ISSUE THREAD

**Issue by TVaakanainen** [Urigo/WhatsApp-Clone-Client-React#922]
The step in the beginning is missing the types-package for react-router-dom which will result into error: `Could not find a declaration file for module 'react-router-dom'.` in build. 

By diff one can see that in tutorial these types are actually installed, but this step is missing in the tutorial code-snippets.

**Comment by Urigo** [comment]
You are right!

Updated and deployed a new `next` version
