### ISSUE TITLE
In step 6's step 6.6 App.tsx-file is missing an update

### ISSUE THREAD

**Issue by TVaakanainen** [Urigo/WhatsApp-Clone-Client-React#924]
In the step 6.6 history-parameter is added to ChatRoomScreenParams, but App.tsx-file is never visibly updated to reflect this change causing a compilation-time error: `Property 'history' is missing in type '{ chatId: string; }' but required in type 'ChatRoomScreenParams'.  TS2741`

**Comment by Urigo** [comment]
You are right!

Updated and deployed a new `next` version
