### ISSUE TITLE
Step 6's step 6.9 unit tests do not fulfil component interfaces completely

### ISSUE THREAD

**Issue by TVaakanainen** [Urigo/WhatsApp-Clone-Client-React#925]
Mock data used in unit tests doesn't completely fulfil the interfaces of their respective components. For example ChatNabar.test.tsx chat-object is missing "messages"-(array) property, and the rendered component is missing history data-property. 

These do not crash the test, but I'm not sure whether it makes sense to omit doing a "full mock", especially since IDEs like Visual Studio Code do see these absences and do render errors (even if they don't cause an error in test-execution).

**Comment by TVaakanainen** [comment]
Also on MessagesList.test.tsx there is a type-missmatch as test sets mocked data-property "createdAt" as a Date-object, but the interface "ChatQueryMessage" seems to define the property as a number.

**Comment by Urigo** [comment]
True, are you on for creating a PR to fix those?

**Comment by TVaakanainen** [comment]
I could try to make it happen on this weekend, unless someone already fixes those before that.

**Comment by milenazuccarelli** [comment]
Also encountered this same problem, currently working on resolving it as well. I also had an issue with using `fetch` in the tests. According to the `jest-fetch-mock` [documentation](https://github.com/jefflau/jest-fetch-mock#typescript-guide), it's recommended to use `fetchMock` in tests, in case anyone else is having this issue 🃏

**Comment by Urigo** [comment]
I've fixed this on master.
Can you check out step 6.9 on Github and ping me if I haven't fixed it correctly?

@milenazuccarelli can you open a separate issue about your issue?
