### ISSUE TITLE
Step 7 is incompatible with latest react-apollo-hooks (0.5.0), but works with 0.4.5

### ISSUE THREAD

**Issue by TVaakanainen** [Urigo/WhatsApp-Clone-Client-React#982]
It seems that if one uses latest react-apollo-hooks (0.5.0) step 7 will crash with an error ```Uncaught TypeError: Cannot read property 'chats' of undefined
    at ChatsList (ChatList.tsx:81)```.

Downgrading to 0.4.5 allows the step to function. I do not know the reason for this, nor have the expertise or time to debug right now. 

I think that the tutorial should be locked to version react-apollo-hooks version 0.4.5 until someone has a moment to figure out what happens and a possible fix is either made to the library or the tutorial is changed in a way that allows it to function with the latest version.

**Comment by Urigo** [comment]
@ardatan already fixed that but I haven't pushed it to the website.
Check the master branch on the repos and let me know if that works for you.
I will push that update in a couple of minutes to the website.
Reopen if it didn't fix it for you

**Comment by pancake-boy** [comment]
i downloaded the lastest release zip and i'm still getting this
https://github.com/Urigo/WhatsApp-Clone-Server/archive/master@step8@next.zip

**Comment by Urigo** [comment]
@TVaakanainen @pancake-boy now it should be fixed as we've moved to the new `@apollo/react-hooks` library
