### ISSUE TITLE
Step 7's step 7.4 unit tests do not fulfil component and function interfaces completely

### ISSUE THREAD

**Issue by TVaakanainen** [Urigo/WhatsApp-Clone-Client-React#983]
```Property 'history' is missing in type '{}' but required in type 'ChatListProps'.```

Line 49 in src/components/ChatsListScreen/ChatsList.test.tsx.

```Expected 1 arguments, but got 0.```

Line 8 in src/App.test.tsx.

Typescript issues visible in VS Code. Do not crash test run-time.

**Comment by Urigo** [comment]
@TVaakanainen care to submit a PR?

**Comment by Urigo** [comment]
I've fixed this on master.
Can you check out step 7.4 on Github and ping me if I haven't fixed it correctly?
