### ISSUE TITLE
Error : useAddChatMutation

### ISSUE THREAD

**Issue by veerjainATgmail** [Urigo/WhatsApp-Clone-Client-React#984]
Failed to compile.

./src/components/ChatCreationScreen/index.tsx
Module not found: **Can't resolve '../../graphql/types**' in xxxxxxxxxxxxxxxxxx/WhatsApp-Clone-Client-React/src/components/ChatCreationScreen'

**useAddChatMutation** not found.

With the latest master...

**Comment by veerjainATgmail** [comment]
folder name mismatch.. thanks.

**Comment by veerjainATgmail** [comment]
Please modify the file codegen.yml 

schema: ../**Whatsapp**-Clone-Server/modules/*/*.ts

to

schema: ../**WhatsApp**-Clone-Server/modules/*/*.ts

**Comment by Urigo** [comment]
@veerjainATgmail good catch!  

Fixed and pushed to master, will be deployed to the website on the next release

Thank you!

**Comment by Urigo** [comment]
released and deployed

**Comment by veerjainATgmail** [comment]
for client, run 
_yarn codegen_ or _yarn run prebuild_
before _yarn start._ 

for server, _yarn start_ takes care of codegen
